# Generated by Django 4.2.4 on 2024-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tags_product_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN'), ('UNISEX', 'UNISEX'), ('CHILD', 'CHILD'), ('NEWBORN', 'NEWBORN')], default='', max_length=50),
        ),
    ]
