# Generated by Django 4.2.4 on 2024-03-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_alter_connect_friends_alter_connect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user', unique=True),
        ),
    ]
