# Generated by Django 4.2.4 on 2024-03-08 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_connect_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
