# Generated by Django 4.2.4 on 2024-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userimage_user'),
        ('chat', '0005_alter_connect_friends_alter_connect_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='reciever', to='users.user'),
        ),
    ]
