# Generated by Django 4.1.13 on 2024-02-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userimage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
