# Generated by Django 4.1.13 on 2024-02-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userimage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userimage",
            name="image",
            field=models.ImageField(
                blank=True,
                default="profiles/avatar.jpg",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
