# Generated by Django 4.1.13 on 2024-02-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("others", "others")],
                default="male",
                max_length=6,
            ),
        ),
    ]
