# Generated by Django 4.2.6 on 2024-02-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_student_admission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='instructors/')),
                ('teacher_email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=64)),
                ('experience', models.TextField()),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=False, max_length=10),
        ),
    ]
